from random import choice

ACTIVITIES_EVENTS = [
    "They came into a large amount of money",
    "They became sick or diseased somehow",
    "A friend betrayed their trust",
    "A stroke of luck aided their pursuit of their goal",
    "They defeated a rival or significant enemy",
    "They made a grave social mistake",
    "A friend or ally was slain or lost to them",
    "They overcame an obstacle to their goal",
    "A source of power they have was threatened",
    "They were defeated by a rival in their ambition",
    "They were accused of a serious crime",
    "They obtained a useful item of magic",
    "They vanished mysteriously for a time",
    "They were attacked by monsters",
    "They made some unsavory associates",
    "They stole something or were robbed in turn",
    "They ventured into dangerous terrain",
    "They offended a powerful entity",
    "A plan of theirs came to its fruition",
    "They gained a powerful new ally",
]
TYPES = {
    "Adventuring Parties": [
        "They’re delving into a perilous Deep",
        "They’ve been savaged by monsters",
        "They slew a powerful foe",
        "They’re quarreling over some treasure",
        "They committed an outrageous social crime",
        "They’re spending huge amounts of money",
        "A member has betrayed the others",
        "They murdered someone important",
        "A promising new member joined them",
        "They’ve gotten or lost a noble patron",
        "They’ve been cursed or blighted by magic",
        "They’re heading into dangerous territory",
    ],
    "Demagogues and Religious Zealots": [
        "A noble patron is finding them useful",
        "Their followers are getting out of hand",
        "They’re picking a fight with existing authority",
        "They’ve made ties with local crime figures",
        "They’ve struck against a hated local figure",
        "They’re spreading an appealing new idea",
        "An important local has joined their cause",
        "They’ve gotten a major donation from believers",
        "They’re being suppressed by local authorities",
        "Followers are arguing over ideological points",
        "They’re trying to create a new power base",
        "They’ve gotten a stroke of divine good fortune",
    ],
    "Nobles and Gentry": [
        "A rival has encroached on their lands or rights",
        "They’re making a familial tie by marriage",
        "A trusted lieutenant has died or betrayed them",
        "They’ve ruthlessly quashed a non-noble rival",
        "A family scion has gotten in big trouble",
        "Their superior has repaid a favor owed them",
        "They’re fighting with a rival local power base",
        "They’ve formed an alliance with a neighbor",
        "An old enemy of their line has struck them",
        "They’re fighting over rights to a particular title",
        "They’ve committed some grave social faux pas",
        "They’ve infuriated their superior somehow",
    ],
    "Warlords and Warband Chiefs": [
        "They’ve attacked a poorly-defended place",
        "They’ve got a promising new lieutenant",
        "One of their underlings betrayed them",
        "Their men went on an undisciplined rampage",
        "They’ve moved their base of operations",
        "They’ve gotten backing from an outside power",
        "They’re trying to become legitimate rulers",
        "They’re infighting over loot, women, or rank",
        "They were badly wounded in a fight",
        "They pulled off a remarkable victory",
        "Their band split due to a quarrel",
        "They absorbed a weaker group",
    ],
    "Merchants and Oligarchs": [
        "A local industry fell under their control",
        "They made a deal with a local crime boss",
        "They bought or built something fabulous",
        "Criminals are assaulting their wealth sources",
        "They cut a very profitable new deal",
        "Their employees or minions are getting restive",
        "They opened a new branch of operations",
        "They made an alliance with a local noble",
        "They’ve enlisted adventurers for dire work",
        "A noble has marked them as a dangerous foe",
        "They drove a rival out of business",
        "Some enterprise of their has collapsed",
    ],
    "Sorcerers and Magic-Users": [
        "They’ve acquired “subjects” for their work",
        "They suffered a magical mishap of some kind",
        "They’ve acquired an esoteric magic item",
        "A rival sorcerer has struck at them",
        "They’ve hired adventurers to acquire something",
        "A noble has enlisted their aid in a cause",
        "They’ve been venturing into ancient ruins",
        "They’ve created a Working to pursue an end",
        "They’re accused of a heinous crime",
        "The locals begged their aid in a time of need",
        "They’ve acquired a promising apprentice",
        "They’ve devised a new and potent magic",
    ],
}

type_key = choice(list(TYPES))

print(f"{type_key}")
print(f"\t{choice(ACTIVITIES_EVENTS)}")
print(f"\t{choice(TYPES[type_key])}")
