from random import choice

DRIVE = [
    "Conquest",
    "Construction",
    "Consumption",
    "Deception",
    "Defilement",
    "Destruction",
    "Domination",
    "Parasitization",
    "Predation",
    "Reproduction",
    "Sadism",
    "Theft",
]
POWER = [
    "Perfectly ordinary beast or person",
    "Minor hero or significant mage",
    "Minor magical beast or construct",
    "Species of magically-potent sentient",
    "Significant magical beast or being",
    "Major hero or famous mage",
    "Hero of a magically-potent species",
    "Regionally-significant magical beast",
    "Legendary magical beast",
    "Legate or famous major hero",
    "Imperator or other demi-divine being",
]
MOVEMENT_POWER = [
    "Flight ability at its movement rate, including the ability to fight on the wing"
    "Passes through any solid object",
    "Ignores a type of solid barrier substance",
    "Extra Move action each round",
    "Movement increased by 50%",
    "It makes Fighting Withdrawals as On Turn actions",
    "Can leap its full movement rate",
    "Can swim, climb, or navigate some other usually-troublesome medium at full speed",
    "It can teleport at its movement rate",
    "Can teleport long distances through shadows, flame, or other characteristic substances",
    "Gets a free Instant Move action when some characteristic event or circumstance obtains",
    "It can split its Move action’s movement around its Main Action",
]
DEBILIITATING_POWER = [
    "Melee or ranged attacks must be rolled twice and the worst hit and damage used",
    "Lose a Move action for the round",
    "Suffer paralysis, unconsciousness, or other fight-ending status after being hit twice with this ability. 5 points if only one hit is needed.",
    "Suffer 1d6 damage/2 HD of the creature when you do a common type of activity",
    "Lose a Main action for the round",
    "Become unable to cast spells or use arts for 1d4 rounds",
    "Suffer double damage from the creature",
    "The power applies a -2 penalty to any saves against it.",
    "The power automatically affects all foes around it, with a save to resist",
    "The penalty lasts longer than just the scene",
    "The power is only usable 1-3 times a fight",
    "Use the power as an On Turn action once per round",
]
AUGMENTING_POWER = [
    "Gain an extra normal attack",
    "Double an attack's normal damage or Shock",
    "Gain a bonus Main Action",
    "Regenerate its HD in lost hit points each round until you're slain",
    "Gain a +4 bonus to AC or become immune to Shock",
    "One attack per round becomes unavoidable",
    "Become immune to certain general types of spells and magical effects",
    "Gain an entire bonus round of action",
    "Automatically succeed at one save per round",
    "The buff trigger lasts only a short while or is difficult to arrange",
    "The buff trigger either lasts a long while once achieved or is not hard to make happen",
    "The creature has to work continuously to maintain or obtain the trigger situation",
    "The buff is normally in effect, either because it's intrinsic or very easy to trigger",
]
INTRINSIC_POWER = [
    "Use a first or second-level spell equivalent",
    "Use a third or fourth-level spell equivalent",
    "Use a fifth level spell equivalent",
    "Use a given spell equivalent at will",
    "Use a given spell equivalent only when the situation is thematically appropriate or a specific trigger situation",
    "Use the spell equivalent as an On Turn action at most once per round",
    "Use a Mage art equivalent once a scene",
    "Use a Mage art equivalent at will",
    "Gain the benefits of one level of a Focus",
    "Be immune to a general class of weapon: piercing, slashing, crushing, or the like",
    "Be immune to non-magical weapons",
    "Require a specific type of weapon or form of injury to harm it",
    "Be immune to an uncommon harm like poison, frost, or electricity",
    "Be immune to a fairly common harm like fire or mind-affecting magic",
    "Be immune to an entire large class of material, such as metal, plant matter, or directly damaging spells",
    "Inflict a particular debuff or damage on those who hit it in melee; if it costs Effort, add the harmful power's cost to this",
]
LOCAL_CONTACT = [
    "The locals have no idea it exists",
    "The locals make wild guesses and myths of it",
    "They've had a few significant encounters",
    "They know it's there and a little of its wants",
    "It's a regular threat they need to deal with",
    "They know its nature and needs very well",
]
LOCAL_REACTION = [
    "They try to placate or appease its hungers",
    "They try to kill it, actively hunting it down",
    "They avoid its territory out of spiritual fear",
    "They accept a certain amount of loss from it",
    "They build countermeasures against it",
    "They try to contain it within a certain area",
    "They try to use it against their enemies",
    "They worship it or take it as a leader",
]
SCARS_LEFT = [
    "Many widows and orphans of its hunters",
    "A grand structure ruined by its acts",
    "Land has been made worthless by its threat",
    "A local hero has been slain by it",
    "Local clergy have been shown as helpless",
    "A local lord has lost much wealth from it",
    "The poorest have suffered most from it",
    "A great plan for the future was ruined by it",
    "A venerated tradition was defiled by it",
    "A vital good or resource was spoiled by it",
]
MONSTER_ORIGIN = [
    "It's a relict of the malice of the Outsiders",
    "It's the product of human sorcerer-kings",
    "It's an accident of magic or nature",
    "It's a decayed form of something once noble",
]
PAST_CONNECTION = [
    "It's a servant of a long-dead religion",
    "It's obedient to a long-gone political group",
    "It's meant to target a perhaps-vanished foe",
    "It feeds on environment that is now rare",
    "It's accepted by certain ancient defenses",
    "It serves an alien or vanished aesthetic end",
    "Its home was a place that is now gone",
    "It seeks something that has since been lost",
    "It seeks victory in a struggle that is now over",
    "It's only part of something, the rest now gone",
    "It serves an urge that no longer makes sense",
    "It was sacred to some group that is now lost",
]
ACTIVITY_TWIST = [
    "Its activities are very useful to some group",
    "It's currently hurting an unsympathetic group",
    "It responds to some ancient plea for help",
    "It targets a group the PCs count as friends",
    "It's friendly to those sharing its tie to the past",
    "A byproduct of its activities is very valuable",
    "It has some devotees or covert minions",
    "It hates something the PCs have or relate to",
    "It was formerly benevolent or useful",
    "A victim plots a desperate act of revenge",
    "Some think it's victims somehow deserved it",
    "Killing it would cause some dire consequence",
    "It's being hunted by something even worse",
    "It has regular cycles of activity and torpor",
    "It has some defensible reason for its acts",
    "It protects or spares its willing subjects",
    "Someone is profiting by its depredations",
    "The locals believe something very false of it",
    "Its damage is insidious and slow to be seen",
    "Hunters quarrel over who is to claim it",
]

for item in [
    DRIVE,
    POWER,
    MOVEMENT_POWER,
    DEBILIITATING_POWER,
    AUGMENTING_POWER,
    INTRINSIC_POWER,
    LOCAL_CONTACT,
    LOCAL_REACTION,
    SCARS_LEFT,
    MONSTER_ORIGIN,
    PAST_CONNECTION,
    ACTIVITY_TWIST,
]:
    print(choice(item))
