from random import choice, randint

portal_type = [
    "Gateway - a typical portal that connects one world to another",
    "Malignancy - a tear in the planes that allows one plane to slowly destroy the other.",
    "Mingling - a powerful correspondence between two planar locales that forms a bond between them.",
    "Vortex - a puncture in the planes, where one plane is draining into another.",
]

malignancy_transformations = [
    "The world melts and shifts, transforming into protoplasmic goop that arranges itself into the invading plane's terrain.",
    "Observers experience a brief blackout as time stops, the world rearranges itself, and time flows forward once again.",
    "Observers are suddenly caught in a black, timeless void. They feel as if they are falling through empty space, when suddenly the altered environment snaps into being around them.",
    "For a brief moment, any observers see the invading plane's terrain around them. These flickers grow longer and more frequent, until they finally end with the new terrain in place.",
    "As soon as the characters look away from a site, it transforms. Even in the briefest moment a location remains out of sight, it changes.",
    "The change appears like a stain spreading across the terrain. The ground shifts, plants and animals transform in an instant, and the invading world overwrites its target.",
    "A powerful storm of energy batters the land. Any terrain struck by its powerful waves slowly changes, with each burst of energy pushing the transformation closer to completion.",
    "The world grows fuzzy and indistinct, as if the characters squinted their eyes. After a few moments, everything grows clear again but has been transformed.",
    "A shrill, piercing noise slowly builds in volume. Even magical or mundane means to block it out, such as a silence spell, fail to diminish its effects. All Listen checks suffer a -1 circumstance penalty per minute the noise persists. After 30 minutes, the noise ends with a thunderous crack. At that moment, the world changes around the characters. As the planes collide and change, the effects of the transformation manifest as sonic energy.",
    "The ground and terrain shudder and move like living organisms. For a brief moment, they lose all color and shape before snapping into the form of the invading plane's terrain.",
]
# prime_element = [
#     'Chaos',
#     'Order',
#     'Good',
#     'Evil',
#     'Earth',
#     'Air',
#     'Water',
#     'Fire',
#     'Life',
#     'Death',
#     'Technology',
#     'Weather',
#     'Altered Gravity',
#     'Altered Orientation',
#     'Other',
# ]
vortex_contents = [
    "Creature: A monster or NPC with a CR equal to the party's level – 2 drifts into view.",
    "Creature: A monster or NPC with a CR equal to the party's level – 1 floats past.",
    "Creature: A monster or NPC with a CR equal to the party's level hurtles by.",
    "Creature: A monster or NPC with a CR equal to the party's level + 1 soars into view.",
    "Creature: A monster or NPC with a CR equal to the party's level + 2 approaches the characters.",
    "Creature: A powerful wizard who seeks to study the vortex inspects a portal near the characters' location.",
    "Creature: A flock of demons, devils, or some other flying outsider on a mission to find a specific portal soars by. The creatures may attack the PCs if they sight them. These creatures should have an EL equal to the party's level + 1d3–1.",
    "Creature: A creature shoots through a nearby portal and lands amidst the characters. It has a CR or level equal to the party's level. The creature could be on the run from its enemies, or it might even have knowledge of the vortex.",
    "Hulk: A battered ship, an entire building, or a similar edifice floats near the characters. Creatures may dwell within it, or it could hold supplies the PCs need, a map of the portals in this area of the vortex, or a powerful, long-lost relic.",
    "Corpse: The dead body of a giant, dragon, titan, or similar monstrous creature floats into view. Smaller creatures may use the body as a home, dwelling within its pockets or even pitching tents in its flesh. A tribe of primitive humanoids could worship the corpse as a god, as they tear flesh from it to eat and even tend mold and giant maggots on its decaying surface.",
    "Bend: The vortex bends sharply in a random direction, giving the characters the chance to swoop close to its side and escape through a portal.",
    "Settlement: Using sovereign glue or similar magical items and spells, a group of creatures has established a settlement anchored to a chain running through a portal. This place could be a prison, a research station, or a forgotten refuge.",
    "Gone Fishing: A group of clever humanoids uses a portal from their world to the vortex to fish for food, captives, and treasure. They use a huge net to reach into the vortex and snatch objects as they fall, relying on leather harnesses and straps to hold themselves in place. The creatures could be cannibalistic savages, curious wizards, or opportunistic thieves.",
    "Debris Field: The characters enter an area of many large boulders, dust, trees, or similar debris that was sucked into the vortex at the same time, keeping the materials together. Flying predators could lurk amongst the debris, or it could serve as a refuge for the PCs.",
    "Energy Storm: A sudden flux of planar energy causes bolts of lightning to arc from one side of the vortex to another. Each PC must make a Reflex save (DC 15) or suffer 2d6 points of electricity damage.",
    "Planar Bridge: An ambitious culture or individual has managed to construct (though not necessarily complete) a bridge between two portals. The bridge might stretch across the vortex, or it could consist of a flight of stairs and a platform perched at the vortex's edge.",
    "Widened Area: The vortex widens by 2d20%.",
    "Narrow Area: The vortex narrows by 2d20%.",
    "Floating Island: A collection of earth and debris has accreted here and spawned a gleaming force bubble that keeps everything within safe from the planar winds. An entire village could thrive on the larger islands.",
]

terrain = [
    "Air",
    "Desert",
    "Flooded",
    "Forest",
    "Jungle",
    "Mechanical",
    "Mountains",
    "Organic",
    "Plains",
    "Splintered",
    "Subterranean",
    "Swamp",
    "Tundra",
    "Water",
]
traits = [
    "Terrain (Gravity)",
    "Chaos (Arcane Instability)",
    "Chaos (Chaos Ascendant)",
    "Chaos (Chaos Lands)",
    "Chaos (Law's Bane)",
    "Cold (Blizzard Conditions)",
    "Cold (Freezing Conditions)",
    "Cold (Snow)",
    "Elemental (Elemental Ascendancy)",
    "Elemental (Elemental Enervation)",
    "Elemental (Elemental Vacuum)",
    "Evil (Clouds of Baneful Influence)",
    "Evil (Empower Evil)",
    "Evil (Hatred of the Land)",
    "Evil (Insidious Weakness)",
    "Evil (Scorn the Righteous)",
    "Good (Glade of Benevolent Charity)",
    "Good (Strength of the Righteous)",
    "Good (Weakness of the Vile)",
    "Heat (Ambient Fire)",
    "Heat (Ash Storms)",
    "Heat (Extreme Heat)",
    "Law (Edict of Law)",
    "Law (Strength of Pattern)",
    "Life (Plague World)",
    "Life (War World)",
    "Light (Glare)",
    "Light (Sunlight)",
    "Magic (Arcane Instability)",
    "Magic (Arcane Potency)",
    "Magic (Arcane Weakness)",
    "Magic (Dead Magic)",
    "Magic (Magical Drought)",
    "Magic (Magical Flux)",
    "Magic (Magical Veil)",
    "Necropetonce (Bane of the Living)",
    "Necropetonce (Kingdom of the Dead)",
    "Necropetonce (March of the Dead)",
    "Necropetonce (Strength of Undeath)",
    "Necropetonce (Shroud of Death)",
    "Technology (Advanced Tech)",
    "Technology (Arcane Masquerade)",
    "Technology (Mechanical Supremacy)",
    "Technology (Technological Aura)",
    "Technology (Technological Virus)",
    "Waterways (Air Currents)",
    "Waterways (Boiling Water)",
    "Waterways (Dust)",
    "Waterways (Magma)",
    "Waterways (Slime)",
    "Weather (Acid Rain)",
    "Weather (Flash Freeze)",
    "Weather (Ghost Wind)",
    "Weather (Rain of Fire)",
]
element = [
    "Acid",
    "Chaotic",
    "Cold",
    "Darkness",
    "Earth",
    "Electricity",
    "Fire",
    "Sonic",
    "Water",
    "Roll twice more",
]
magic_school = [
    "Abjuration",
    "Conjuration",
    "Divination",
    "Enchantment",
    "Evocation",
    "Illusion",
    "Necromancy",
    "Transmutation",
    "Acid",
    "Chaotic",
    "Cold",
    "Darkness",
    "Death",
    "Electricity",
    "Evil",
    "Fear",
    "Fire",
    "Force",
    "Good",
    "Lawful",
    "Light",
    "Mind-affecting",
    "Sonic",
    "Teleportation",
    "Roll twice more",
]
trait_strength = ["Faint", "Light", "Medium", "Heavy", "Overwhelming"]

type_of_portal = choice(portal_type)

print(type_of_portal)

if type_of_portal.startswith("Malignancy"):
    print(choice(malignancy_transformations))

if type_of_portal.startswith("Vortex"):
    print(choice(vortex_contents))

for item in [terrain, traits, element, magic_school]:
    if randint(0, 1) > 0:
        print(f"{choice(item)} - {choice(trait_strength)}")
